Change Spek JVM runtime to create path one time only on discovery.
JetBrains/spek pull request #299
Opened 2017-10-22 17:30 UTC by ming13

2017-10-23 00:29 UTC, raniejade approved these changes

2017-10-23 00:51 UTC, artem-zinnatullin commented
Uhh, TC just doesn't see this branch no matter what I do

2017-10-24 11:51 UTC, artem-zinnatullin approved these changes

2017-10-24 12:06 UTC, artem-zinnatullin requested changes
Can you please update code to use `PathBuilder`?

2017-10-24 12:06 UTC, artem-zinnatullin commented on spek-runtimes/jvm/src/main/kotlin/org/spekframework/spek2/runtime/SpekJvmRuntime.kt
> +                klass to JvmPathBuilder.from(klass).build()
```console
Unresolved reference: JvmPathBuilder
```

There is no more `JvmPathBuilder`, it's now just `PathBuilder` implemented for every platform :)

2017-10-24 12:06 UTC, artem-zinnatullin commented
CI to the rescue!

2017-10-24 17:05 UTC, ming13 commented
@artem-zinnatullin, damn, these kids grow up fast. Should be fine by now.

2017-10-24 18:28 UTC, artem-zinnatullin approved these changes

2017-10-24 18:28 UTC, merged