Remove experimental annotation from non-experimental classes.
JetBrains/spek pull request #428
Opened 2018-06-13 18:30 UTC by ming13

The only remaining `@Experimental` consumer is `InstanceFactory`. Really not sure if we need it at all since I don’t see a lot of usage here. It is kind of superseded by `Root.registerListener` from my  point of view. WDYT?

Also moved `@Ignore` to `.meta`, but we need to rethink the packaging a bit (or not).

2018-06-13 19:08 UTC, artem-zinnatullin approved these changes

2018-06-14 05:25 UTC, raniejade requested changes

2018-06-14 05:25 UTC, raniejade commented on spek-dsl/common/src/main/kotlin/org/spekframework/spek2/style/gherkin/Gherkin.kt
> +        test("And $description", body = body)
Accidental change?

2018-06-14 06:08 UTC, ming13 commented on spek-dsl/common/src/main/kotlin/org/spekframework/spek2/style/gherkin/Gherkin.kt
> +        test("And $description", body = body)
Yep! Thanks, removed it.

2018-06-14 09:23 UTC, raniejade approved these changes
`InstanceFactory`is used in cases you want to control the classloader used to run the tests.

2018-06-14 10:17 UTC, ming13 commented
> InstanceFactoryis used in cases you want to control the classloader used to run the tests.

@raniejade, yep, but in which cases do you want to control that?

2018-06-14 10:17 UTC, merged

2018-06-14 10:39 UTC, raniejade commented
Robolectric tests for example.